import axios from "axios";
import dotenv from "dotenv";
import Chat from "../Models/ChatModel.js";
import { GoogleGenerativeAI } from "@google/generative-ai";

dotenv.config();

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

export const search = async (req, res) => {
  try {
    const userId = req.user.id; // from token

    if (!userId) {
      return res.status(400).json({ success: false, message: "userId is required" });
    }

    // 1️⃣ Fetch user's latest chat document
    const chatDoc = await Chat.findOne({ userId }).sort({ "sessions.startedAt": -1 });

    if (!chatDoc || !chatDoc.sessions?.length) {
      return res.status(404).json({ success: false, message: "No chat history found for user." });
    }

    // 2️⃣ Get the most recent session
    const recentSession = chatDoc.sessions.reduce((latest, session) => {
      return new Date(session.startedAt) > new Date(latest.startedAt) ? session : latest;
    }, chatDoc.sessions[0]);

    const chatText = recentSession.messages.map(m => m.content).join(" ");

    // 3️⃣ Generate relevant tags using Gemini
    const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash" });
    const prompt = `
      Based on the user's recent chat, extract 3–5 short, lowercase tags 
      that represent the user's emotional or mental health topics.
      Return only a JSON array of tags (no extra text).

      Chat:
      """${chatText}"""
    `;

    const tagResponse = await model.generateContent(prompt);

    let tags = [];
    try {
      const raw = tagResponse.response.text().trim();
      // Extract JSON array even if extra text exists
      const match = raw.match(/\[.*\]/s); 
      if (match) {
        tags = JSON.parse(match[0]);
      } else {
        tags = ["mental health"];
      }
    } catch (err) {
      console.error("⚠️ Error parsing Gemini output:", tagResponse.response.text());
      tags = ["mental health"];
    }

    console.log("🎯 Generated Tags:", tags);

    // 4️⃣ Fetch YouTube videos concurrently for each tag
    const apiKey = process.env.YOUTUBE_API_KEY;
    const youtubeApiUrl = "https://www.googleapis.com/youtube/v3/search";

    const videoPromises = tags.map(async (tag) => {
      const ytResponse = await axios.get(youtubeApiUrl, {
        params: {
          part: "snippet",
          q: `${tag} mental health`,
          type: "video",
          maxResults: 5,
          key: apiKey,
        },
      });

      return ytResponse.data.items.map((item) => ({
        tag, // Gemini-generated tag
        videoId: item.id.videoId,
        title: item.snippet.title,
        thumbnail: item.snippet.thumbnails.medium.url,
        channelTitle: item.snippet.channelTitle,
        url: `https://www.youtube.com/watch?v=${item.id.videoId}`,
      }));
    });

    const allVideos = (await Promise.all(videoPromises)).flat();

    // 5️⃣ Respond with Gemini tags + videos
    return res.json({
      success: true,
      data: {
        tags,       // all tags generated by Gemini
        videos: allVideos,
      },
    });
  } catch (error) {
    console.error("❌ Error:", error.response?.data || error.message);
    return res.status(500).json({
      success: false,
      message: "Error fetching YouTube videos.",
      error: error.message,
    });
  }
};
